#!

using System.Diagnostics;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

const string Api = "https://api.corona.studio/Build/get/latest/all/stable";

// Map upstream runtime names to Nix systems. Windows builds are intentionally
// skipped: they are packaged for distribution only.
var systems = new Dictionary<string, string>
{
    ["linux-x64"] = "x86_64-linux",
    ["linux-arm64"] = "aarch64-linux",
    ["osx-x64"] = "x86_64-darwin",
    ["osx-arm64"] = "aarch64-darwin",
};

using var client = new HttpClient();
var all = await client.GetFromJsonAsync(Api, SerializerContext.Default.ListBuild) ?? [];

var latest = all
    .Where(b => systems.ContainsKey(b.Runtime))
    .GroupBy(b => b.Runtime)
    .Select(g => g.MaxBy(b => b.ReleaseDate, StringComparer.Ordinal)!)
    .OrderBy(b => systems[b.Runtime]);

var sb = new StringBuilder();
sb.AppendLine("# Generated by generator.cs - do not update manually!");
sb.AppendLine($"# Last updated: {DateTime.UtcNow:yyyy-MM-dd}");
sb.AppendLine("{");
foreach (var b in latest)
{
    var url = $"https://api.corona.studio/Build/get/{b.Id}";
    var hash = await PrefetchHashAsync(url);
    sb.AppendLine($"  {systems[b.Runtime]} = {{");
    sb.AppendLine($"    url = \"{url}\";");
    sb.AppendLine($"    hash = \"{hash}\";");
    sb.AppendLine($"    version = \"stable-{b.ReleaseDate.Replace(':', '-')}\";");
    sb.AppendLine("  };");
}
sb.AppendLine("}");

await File.WriteAllTextAsync("package/builds.nix", sb.ToString());
Console.WriteLine("Wrote package/builds.nix");

async Task<string> PrefetchHashAsync(string url)
{
    var psi = new ProcessStartInfo("nix", ["store", "prefetch-file", "--json", url])
    {
        RedirectStandardOutput = true,
    };
    using var proc = Process.Start(psi)!;
    var stdout = await proc.StandardOutput.ReadToEndAsync();
    await proc.WaitForExitAsync();
    if (proc.ExitCode != 0)
    {
        throw new Exception($"nix store prefetch-file failed ({proc.ExitCode}) for {url}");
    }
    return JsonSerializer.Deserialize(stdout, SerializerContext.Default.PrefetchResult)!.Hash;
}

sealed record Build(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("releaseDate")] string ReleaseDate,
    [property: JsonPropertyName("runtime")] string Runtime
);

sealed record PrefetchResult(
    [property: JsonPropertyName("hash")] string Hash
);

[JsonSerializable(typeof(List<Build>))]
[JsonSerializable(typeof(PrefetchResult))]
partial class SerializerContext : JsonSerializerContext;
