# Generated by generator.cs - do not update manually!
# Last updated: 2026-10-01
{
  aarch64-darwin = {
    url = "https://api.corona.studio/Build/get/7e63b58f-6413-4c0a-a279-0e4cffc97db2";
    hash = "sha256-JADV46lgvGOFqqfEX0FO9nOwrUbECEFGWWH2pBd9u9M=";
    version = "stable-2026-10-01T05-31-38";
  };
  aarch64-linux = {
    url = "https://api.corona.studio/Build/get/de5a3df4-d51e-4156-92cc-07028c4ea4f3";
    hash = "sha256-AcUprG0X+5q7YcU43o7LMlN0nS2jzf/SHe/tnCNj2a8=";
    version = "stable-2026-10-01T05-31-38";
  };
  x86_64-darwin = {
    url = "https://api.corona.studio/Build/get/b8cb35df-de1c-45e1-9eb0-2775a3ad0aab";
    hash = "sha256-GlBknz2kvKRdMF2EwtIZsKuYXoR3+AUsy0REBoPlevU=";
    version = "stable-2026-10-01T05-31-38";
  };
  x86_64-linux = {
    url = "https://api.corona.studio/Build/get/68817072-c920-4868-96b2-3267c2db89cd";
    hash = "sha256-s5TYUAO4l+2eQXkzIDvheAIL67pt4K83RXPfoHIGYyk=";
    version = "stable-2026-10-01T05-31-38";
  };
}
