#!

#:package CliWrap@3.10.4

using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

using CliWrap;
using CliWrap.Buffered;

const string Api = "https://api.corona.studio/Build/get/latest/all/stable";

// Only Linux is packaged (NixOS needs the binary patched); macOS and Windows
// builds are intentionally skipped.
var systems = new Dictionary<string, string>
{
    ["linux-x64"] = "x86_64-linux",
    ["linux-arm64"] = "aarch64-linux",
};

using var client = new HttpClient();
var all = await client.GetFromJsonAsync(Api, SerializerContext.Default.ListBuild) ?? [];

var latest = all
    .Where(b => systems.ContainsKey(b.Runtime))
    .GroupBy(b => b.Runtime)
    .Select(g => g.MaxBy(b => b.ReleaseDate, StringComparer.Ordinal)!)
    .OrderBy(b => systems[b.Runtime]);

var sb = new StringBuilder();
sb.AppendLine("# Generated by generator.cs - do not update manually!");
sb.AppendLine($"# Last updated: {DateTime.UtcNow:yyyy-MM-dd}");
sb.AppendLine("{");
foreach (var b in latest)
{
    var url = $"https://api.corona.studio/Build/get/{b.Id}";
    var result = await Cli.Wrap("nix")
        .WithArguments([ "store", "prefetch-file", "--json", url ])
        .WithValidation(CommandResultValidation.ZeroExitCode)
        .ExecuteBufferedAsync();
    var hash = JsonSerializer.Deserialize(result.StandardOutput, SerializerContext.Default.PrefetchResult)!.Hash;

    sb.AppendLine($"  {systems[b.Runtime]} = {{");
    sb.AppendLine($"    url = \"{url}\";");
    sb.AppendLine($"    hash = \"{hash}\";");
    sb.AppendLine($"    version = \"stable-{b.ReleaseDate.Replace(':', '-')}\";");
    sb.AppendLine("  };");
}
sb.AppendLine("}");

await File.WriteAllTextAsync("package/sources.nix", sb.ToString());
Console.WriteLine("Wrote package/sources.nix");

sealed record Build(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("releaseDate")] string ReleaseDate,
    [property: JsonPropertyName("runtime")] string Runtime
);

sealed record PrefetchResult(
    [property: JsonPropertyName("hash")] string Hash
);

[JsonSerializable(typeof(List<Build>))]
[JsonSerializable(typeof(PrefetchResult))]
partial class SerializerContext : JsonSerializerContext;
